development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: SkiBus_development
  pool: 5
  username: johncapecelatro
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: SkiBus_test
  pool: 5
  username: johncapecelatro
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: SkiBus_production
  pool: 5
  username: johncapecelatro
  password:
