development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: Ski Bus_development
  pool: 5
  username: johncapecelatro
  password:

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: Ski Bus_test
  pool: 5
  username: johncapecelatro
  password:

production:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: Ski Bus_production
  pool: 5
  username: johncapecelatro 
  password:
